spring:
  application:
    name: tikax

  security:
    user:
      name: user
      password: 123456
      roles: ADMIN

  datasource:
    url: jdbc:mysql://localhost:3306/yu_blog?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 123456  # ← 改成你的密码
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    #驼峰映射配置
    map-underscore-to-camel-case: true