spring:
  application:
    name: tikax
  security:
    user:
      name: user
      password: 123456
      roles: USER
  datasource:
    url: jdbc:mysql://localhost:3306/titax?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080

mybatis:
  configuration:
    map-underscore-to-camel-case: true

minio:
  endpoint: http://127.0.0.1:9000
  access-key: admin
  secret-key: password
  bucket-name: tikax

logging:
  level:
    anthony.tikax.mapper: debug

  file:
    name: G:/logs/titax/app.log         # 日志输出路径

  logback:
    rollingpolicy:
      max-file-size: 10MB       # 单个文件最大 10MB
      max-history: 7            # 保留 7 个历史文件
      total-size-cap: 1GB    # 总日志大小上限